import 'dart:async';
import 'dart:typed_data';
import 'package:google_generative_ai/google_generative_ai.dart';
import 'package:youtube_explode_dart/youtube_explode_dart.dart';
import 'package:sumquiz/models/extraction_result.dart';
import 'package:sumquiz/services/enhanced_ai_service.dart';
import 'package:sumquiz/utils/cancellation_token.dart';
import 'ai_base_service.dart';
import 'ai_config.dart';
import 'dart:developer' as developer;

class YouTubeAIService extends AIBaseService {
  Future<Result<ExtractionResult>> analyzeVideo(
    String videoUrl, {
    CancellationToken? cancelToken,
  }) async {
    if (!_isValidYouTubeUrl(videoUrl)) {
      return Result.error(EnhancedAIServiceException(
        'Invalid YouTube URL format.',
        code: 'INVALID_URL',
      ));
    }

    final yt = YoutubeExplode();
    try {
      final videoId = _extractVideoId(videoUrl);
      if (videoId == null) throw Exception('Could not extract video ID.');

      developer.log('Fetching video metadata for $videoId',
          name: 'YouTubeAIService');
      final video = await yt.videos
          .get(videoId)
          .timeout(Duration(seconds: AIConfig.transcriptTimeoutSeconds));

      final duration = video.duration ?? Duration.zero;
      final isShort =
          duration.inSeconds < AIConfig.youtubeMultimodalThresholdSeconds;

      if (isShort) {
        developer.log(
            'Mode A: Short video (${duration.inSeconds}s). Fetching audio for multimodal analysis...',
            name: 'YouTubeAIService');
        try {
          cancelToken?.throwIfCancelled();

          final manifest = await yt.videos.streamsClient.getManifest(videoId);
          final audioStreamInfo = manifest.audioOnly.withHighestBitrate();
          final stream = yt.videos.streamsClient.get(audioStreamInfo);

          final List<int> bytes = [];
          await for (final chunk in stream) {
            cancelToken?.throwIfCancelled();
            bytes.addAll(chunk);
          }
          final audioData = Uint8List.fromList(bytes);
          final mimeType = 'audio/${audioStreamInfo.container.name}';

          final result = await _analyzeWithGeminiModeA(
            videoUrl,
            audioData,
            mimeType,
            cancelToken: cancelToken,
          ).timeout(Duration(seconds: AIConfig.youtubeTimeoutSeconds));

          if (result != null && result.text.trim().length >= 100) {
            return Result.ok(result);
          }
        } catch (e) {
          developer.log('Mode A failed: $e. Falling to Mode B/C.',
              name: 'YouTubeAIService');
        }
      }

      developer.log('Using Transcript Pipeline (Mode B/C)...',
          name: 'YouTubeAIService');
      cancelToken?.throwIfCancelled();

      final transcriptData = await _getRawTranscript(yt, videoId);
      if (transcriptData == null || transcriptData.trim().isEmpty) {
        return Result.error(EnhancedAIServiceException(
            'Could not find captions for this video. Use shorter videos or those with available transcripts.',
            code: 'NO_CAPTIONS'));
      }

      final cappedTranscript = transcriptData.length > AIConfig.maxInputLength
          ? transcriptData.substring(0, AIConfig.maxInputLength)
          : transcriptData;

      final refinedResult = await _analyzeWithGeminiModeC(
          cappedTranscript, video.title, videoUrl,
          cancelToken: cancelToken);

      if (refinedResult != null) {
        return Result.ok(refinedResult);
      }

      return Result.ok(ExtractionResult(
        text: cappedTranscript,
        suggestedTitle: video.title,
        sourceUrl: videoUrl,
      ));
    } on CancelledException {
      return Result.error(
          EnhancedAIServiceException('Cancelled by user.', code: 'CANCELLED'));
    } catch (e) {
      developer.log('YouTube analysis failed: $e',
          name: 'YouTubeAIService', error: e);
      return Result.error(EnhancedAIServiceException(
          'YouTube extraction failed. The video may be restricted, too long, or have disabled captions.',
          code: 'EXTRACTION_FAILED'));
    } finally {
      yt.close();
    }
  }

  Future<String?> _getRawTranscript(YoutubeExplode yt, String videoId) async {
    try {
      final manifest = await yt.videos.closedCaptions
          .getManifest(videoId)
          .timeout(Duration(seconds: AIConfig.transcriptTimeoutSeconds));

      if (manifest.tracks.isEmpty) return null;

      ClosedCaptionTrackInfo? trackInfo;
      try {
        trackInfo = manifest.tracks.firstWhere(
            (t) => t.language.code.startsWith('en') && !t.isAutoGenerated);
      } catch (_) {
        try {
          trackInfo = manifest.tracks.firstWhere((t) => !t.isAutoGenerated);
        } catch (_) {
          try {
            trackInfo = manifest.tracks
                .firstWhere((t) => t.language.code.startsWith('en'));
          } catch (_) {
            trackInfo = manifest.tracks.first;
          }
        }
      }

      final captions = await yt.videos.closedCaptions
          .get(trackInfo)
          .timeout(Duration(seconds: AIConfig.transcriptTimeoutSeconds));
      return captions.captions.map((c) => c.text).join(' ');
    } catch (e) {
      return null;
    }
  }

  Future<ExtractionResult?> _analyzeWithGeminiModeA(
    String videoUrl,
    Uint8List audioData,
    String mimeType, {
    CancellationToken? cancelToken,
  }) async {
    if (!await ensureInitialized()) return null;

    final prompt = '''Extract educational content from this video.
    URL: $videoUrl
    
    REQUIREMENTS:
    - suggestedTitle: Descriptive and clean.
    - text: Comprehensive extracted facts and concepts in Markdown.
    - Remove all non-educational filler (ads, intros, etc.).''';

    final response = await generateWithData(
      prompt,
      audioData,
      mimeType,
      customModel: extractorModel,
      cancelToken: cancelToken,
      generationConfig: GenerationConfig(
        responseMimeType: 'application/json',
        responseSchema: Schema.object(
          properties: {
            'suggestedTitle': Schema.string(),
            'text': Schema.string(),
          },
          requiredProperties: ['suggestedTitle', 'text'],
        ),
      ),
    );

    final jsonStr = extractJson(response);
    final data = safeJsonDecode(jsonStr);
    final content = data['text']?.toString() ?? '';
    if (content.isEmpty) return null;

    return ExtractionResult(
      text: content,
      suggestedTitle: data['suggestedTitle']?.toString() ?? 'YouTube Analysis',
      sourceUrl: videoUrl,
    );
  }

  Future<ExtractionResult?> _analyzeWithGeminiModeC(
      String transcript, String title, String videoUrl,
      {CancellationToken? cancelToken}) async {
    if (!await ensureInitialized()) return null;

    final prompt =
        '''Refine this YouTube transcript into a high-quality study guide.
    VIDEO TITLE: $title
    TRANSCRIPT: $transcript
    
    REQUIREMENTS:
    - suggestedTitle: Professional and clear.
    - content: Structured Markdown guide with facts, definitions, and formulas.
    - Tone: Academic and exam-focused.''';

    final response = await generateWithRetry(
      prompt,
      customModel: extractorModel,
      cancelToken: cancelToken,
      generationConfig: GenerationConfig(
        responseMimeType: 'application/json',
        responseSchema: Schema.object(
          properties: {
            'suggestedTitle': Schema.string(),
            'content': Schema.string(),
          },
          requiredProperties: ['suggestedTitle', 'content'],
        ),
      ),
    );

    final jsonStr = extractJson(response);
    final data = safeJsonDecode(jsonStr);
    final content = data['content']?.toString() ?? '';
    if (content.isEmpty) return null;

    return ExtractionResult(
      text: content,
      suggestedTitle: data['suggestedTitle']?.toString() ?? title,
      sourceUrl: videoUrl,
    );
  }

  bool _isValidYouTubeUrl(String url) {
    try {
      final uri = Uri.parse(url);
      final validDomains = [
        'youtube.com',
        'www.youtube.com',
        'youtu.be',
        'm.youtube.com'
      ];
      if (!validDomains.contains(uri.host)) return false;
      return uri.path.contains('/watch') ||
          uri.path.contains('/shorts') ||
          uri.path.contains('/live') ||
          uri.host.contains('youtu.be');
    } catch (_) {
      return false;
    }
  }

  String? _extractVideoId(String url) {
    try {
      final uri = Uri.parse(url);
      if (uri.host.contains('youtu.be')) {
        return uri.pathSegments.isNotEmpty ? uri.pathSegments.first : null;
      }
      if (uri.queryParameters.containsKey('v')) {
        return uri.queryParameters['v'];
      }
      if (uri.path.contains('/shorts/')) {
        final segments = uri.pathSegments;
        final index = segments.indexOf('shorts');
        if (index != -1 && index + 1 < segments.length) {
          return segments[index + 1];
        }
      }
      if (uri.path.contains('/live/')) {
        final segments = uri.pathSegments;
        final index = segments.indexOf('live');
        if (index != -1 && index + 1 < segments.length) {
          return segments[index + 1];
        }
      }
      return null;
    } catch (_) {
      return null;
    }
  }
}
